// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_basic_linear(t,n,i){function s(n,i,s,e){t.support.transform&&t.support.transition?(i.right&&(i.left=-i.right,delete i.right),i.transform="translate3d("+i.left+"px,0,0)",delete i.left,i.transition="all "+s+"ms cubic-bezier(0.770, 0.000, 0.175, 1.000)",n.css(i),e&&n.on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",function(){n.css({transform:"",transition:""}),n.off("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd"),e()})):n.animate(i,{easing:"easeInOutExpo",duration:t.duration,complete:e?e:0})}var e=jQuery,o=e(this),a=e("<div>").addClass("ws_effect").css({position:"absolute",display:"none","z-index":2,width:"200%",height:"100%",transform:"translate3d(0,0,0)"}).appendTo(i),r=e("<div>").css({position:"absolute",left:"auto",top:"auto",width:"50%",height:"100%",overflow:"hidden"}),d=r.clone();a.append(r,d),this.go=function(l,f){a.stop(1,1);var c=!!((l-f+1)%n.length)^t.revers?"left":"right";e(n[f]).clone().appendTo(r).css(c,0),e(n[l]).clone().appendTo(d).show(),"right"==c?(r.css("left","50%"),d.css("left",0)):(r.css("left",0),d.css("left","50%")),a.css({left:"auto",right:"auto",top:0}).css(c,0).show();var h={};h[c]=-i.width(),s(a,h,t.duration,function(){o.trigger("effectEnd"),a.hide().find("div").html("")})}}// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 2.2
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
wowReInitor(jQuery("#wowslider-container1"),{effect:"basic_linear",prev:"",next:"",duration:10*100,delay:20*100,width:960,height:360,autoPlay:true,stopOnHover:true,loop:false,bullets:true,caption:true,controls:true,logo:"engine1/loading.gif",images:0});